### ISSUE TITLE
Custom Fields Improvements

### ISSUE THREAD

**Issue by SiamKreative** [ThemeAvenue/Awesome-Support#143] opened 2015-05-18 09:54 UTC
## Add rows attribute for textarea

The textarea field, which is not documented, should have an additional parameters: the amount of rows for the textarea.

## Add input type date

This could be useful for all kind of date (purchase, expiry, contract, etc.). Browser support is [very limited](http://caniuse.com/#feat=input-datetime) and therefore, we would need to add a [jQuery datepicker](http://amsul.ca/pickadate.js/). For the dashboard, we should be able to use jQuery UI, like so:
```php
wp_enqueue_script('jquery-ui-datepicker');
wp_enqueue_style('jquery-style', 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/themes/smoothness/jquery-ui.css');
```

## Add HTML5 pattern attribute

In some cases it could be useful to be able to add a [validation pattern](http://www.w3schools.com/tags/att_input_pattern.asp). This allows easy front-end validation for supported browsers. This should be fairly easy to implement.

![image](https://cloud.githubusercontent.com/assets/1778633/7678483/aacacfc6-fd7e-11e4-84d6-6220167be92e.png)

## Add layout options for front-end

Multiple custom fields makes the page way too long and boring. We need to add the ability to customize the layout of the form. How about an option like `column_size: 1/2 1/3 2/3`? This could be combined with a `clearfix` function that would allow to clear the float between custom fields.

**Comment by SiamKreative** [comment] 2015-06-29 04:58
To allow layout flexibility, perhaps we could use something like this:

![image](https://cloud.githubusercontent.com/assets/1778633/8401231/ec344b0c-1e55-11e5-97db-033a679f70f5.png)

**Comment by SiamKreative** [comment] 2015-07-02 02:24
### Add new types & options
- [ ] Textarea > Rows option
- [ ] Date
- [ ] Multiple select
- [ ] Checkboxe
- [ ] Radio
- [ ] Colorpicker?

### Improve documentation
For the [custom fields parameters](https://getawesomesupport.com/documentation/awesome-support/custom-fields/), it would be better to have it in a table, to show the default value and type of data (bool / string)

**Comment by julien731** [comment] 2015-07-02 03:11
This is a duplicate of #44

**Closed** 2015-09-15 10:36 UTC
Labels: enhancement
