### ISSUE TITLE
TinyMCE related

### ISSUE THREAD

**Issue by wpvipteam** [ThemeAvenue/Awesome-Support#96] opened 2015-02-27 15:08 UTC
The problem with the formatting of messages in the email settings. Messages on page does not look bad. But email does not retain formatting what's in the settings.

**Comment by SiamKreative** [comment] 2015-03-02 05:14
This is a duplicate of https://wordpress.org/support/topic/tinymce-related-1?replies=1

**Closed by SiamKreative** 2015-03-02 05:14 UTC
