### ISSUE TITLE
Performance: HTTP Request on every admin site

### ISSUE THREAD

**Issue by eteubert** [ThemeAvenue/Awesome-Support#121] opened 2015-04-20 08:27 UTC
Using the plugin "Query Monitor" I realized that there is a HTTP request going out on every admin request, creating a huge slowdown. Can this be avoided?

![portfolio_ _podlove_podcast_publisher_ _wordpress](https://cloud.githubusercontent.com/assets/235918/7226283/07886fa4-e77a-11e4-801c-26923bb9bd52.png)

**Comment by julien731** [comment] 2015-04-21 09:19
Thanks for reporting this issue. After investigating it, I realized that it's caused by a bug in [Remote Dashboard Notification](https://github.com/ThemeAvenue/Remote-Dashboard-Notifications). The bug was already fixed in the master branch but no update was pushed. I'm cleaning the plugin right now and will push an update today. There will also be an update to Awesome Support soon.

**Closed by julien731** 2015-04-21 09:19 UTC

**Comment by eteubert** [comment] 2015-04-21 11:39
Thanks! :)
