### ISSUE TITLE
AS Notification Plugin generated 222 characters of unexpected output

### ISSUE THREAD

**Issue by TheZoker** [ThemeAvenue/Awesome-Support#82] opened 2015-02-11 17:43 UTC
Hi there,

I bought your notification plugin today and activated it.
I got this error:
>The plugin generated 222 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

Can you please fix that?

**Comment by julien731** [comment] 2015-02-11 17:44
Damn. I think I read that somewhere else too. However, did the add-on activate or not at all?

**Comment by TheZoker** [comment] 2015-02-11 17:45
Yes it was activated, but I guess that this error is not unimportant...

**Comment by julien731** [comment] 2015-02-11 17:46
Indeed I need to find the cause. Will be investigating.

**Comment by TheZoker** [comment] 2015-02-11 17:49
Thank you :) Additional you should link to the page, where the user can find the slack webhook url ;)

**Comment by julien731** [comment] 2015-02-11 17:49
:+1:

**Comment by SiamKreative** [comment] 2015-03-04 02:45
I have been unable to replicate this issue with the latest version of the plugin (3.1.4). I'm closing this for now (but it has been referenced).

**Closed by SiamKreative** 2015-03-04 02:45 UTC
Labels: addon, bug
